wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
batch_size:
  desc: null
  value: 100
channels:
  desc: null
  value:
  - 16
  - 32
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: adam
optimizer_type:
  desc: null
  value: sgd
